"""
Module for opening the data files generated from the `process` script
on the laptop from the TACTIC lab.

(TODO: put that code in this repository too)
"""

from dataclasses import dataclass
from typing import List
import numpy as np
import matplotlib.pyplot as plt


@dataclass
class Event:
    """for storing data from `process` output files"""
    times: np.ndarray
    amps: np.ndarray
    number: int
    channels = np.array(list(range(32)))
    

def read(filename):
    """
    Read output.txt files generated by the `process` script.

    Each line in the file is of the form 'time voltage time voltage ....'
    for all the channels (channel = strip number, not digitizer channel)
    """
    with open(filename, "r+", encoding="utf-8") as peak_file:
        lines = peak_file.readlines()
    events: List[Event] = []
    for event_num, event_line in enumerate(lines):
        words = list(map(float, event_line.split()))
        assert len(words) == 32*2  # 32 channels, time and amplitude
        times = np.array(words[0::2])
        amplitudes = np.array(words[1::2])
        events.append(Event(times, amplitudes, event_num))
    return events

if __name__ == "__main__":
    events = read("analysis/output_1100.txt")
    plt.scatter(events[0].times, events[0].amps)
    plt.show()